### ISSUE TITLE
Python extension does not load/Python Tools server crashes

### ISSUE THREAD

**Issue by brettcannon** [Microsoft/python-language-server#474]
@isurugiu commented on [Sat Dec 08 2018](https://github.com/Microsoft/vscode-python/issues/3601)

## Environment data

- VS Code version: 1.29.1
- Extension version (available under the Extensions sidebar): 2018.11.0
- OS and version: Windows 10 x64
- Python version (& distribution if applicable, e.g. Anaconda): 3.7.1
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
- Relevant/affected Python packages and their versions: XXX

## Expected behavior

Python extension/language server starts successfully

## Actual behavior
VS Code produces the following error
```The Python Tools server crashed 5 times in the last 3 minutes. The server will not be restarted.```

## Steps to reproduce:

Follow the steps at https://code.visualstudio.com/docs/python/python-tutorial#_prerequisites

## Logs
```
Starting Microsoft Python language server.
Error:
  An assembly specified in the application dependencies manifest (Microsoft.Python.LanguageServer.deps.json) was not found:
    package: 'System.IO.Pipelines', version: '4.5.1'
    path: 'lib/netcoreapp2.1/System.IO.Pipelines.dll'
[Info  - 9:52:18 PM] Connection to server got closed. Server will restart.
Error:
  An assembly specified in the application dependencies manifest (Microsoft.Python.LanguageServer.deps.json) was not found:
    package: 'System.IO.Pipelines', version: '4.5.1'
    path: 'lib/netcoreapp2.1/System.IO.Pipelines.dll'
[Info  - 9:52:18 PM] Connection to server got closed. Server will restart.
Error:
  An assembly specified in the application dependencies manifest (Microsoft.Python.LanguageServer.deps.json) was not found:
    package: 'System.IO.Pipelines', version: '4.5.1'
    path: 'lib/netcoreapp2.1/System.IO.Pipelines.dll'
[Info  - 9:52:18 PM] Connection to server got closed. Server will restart.
Error:
  An assembly specified in the application dependencies manifest (Microsoft.Python.LanguageServer.deps.json) was not found:
    package: 'System.IO.Pipelines', version: '4.5.1'
    path: 'lib/netcoreapp2.1/System.IO.Pipelines.dll'
[Info  - 9:52:18 PM] Connection to server got closed. Server will restart.
Error:
  An assembly specified in the application dependencies manifest (Microsoft.Python.LanguageServer.deps.json) was not found:
    package: 'System.IO.Pipelines', version: '4.5.1'
    path: 'lib/netcoreapp2.1/System.IO.Pipelines.dll'
[Error - 9:52:18 PM] Connection to server got closed. Server will not be restarted.
```

Output from `Console` under the `Developer Tools` panel (toggle Developer Tools on under `Help`)

```
log.ts:157  INFO no standard startup: panel is active
TMSyntax.ts:47 Overwriting grammar scope name to file mapping for scope source.python.
Old grammar file: file:///c%3A/Program%20Files/Microsoft%20VS%20Code/resources/app/extensions/python/syntaxes/MagicPython.tmLanguage.json.
New grammar file: file:///c%3A/Users/iulian/.vscode/extensions/magicstack.magicpython-1.1.0/grammars/MagicPython.tmLanguage
e.register @ TMSyntax.ts:47
TMSyntax.ts:47 Overwriting grammar scope name to file mapping for scope source.python.
Old grammar file: file:///c%3A/Users/iulian/.vscode/extensions/magicstack.magicpython-1.1.0/grammars/MagicPython.tmLanguage.
New grammar file: file:///c%3A/Users/iulian/.vscode/extensions/tht13.python-0.2.3/syntaxes/python.tmLanguage
e.register @ TMSyntax.ts:47
TMSyntax.ts:47 Overwriting grammar scope name to file mapping for scope source.regexp.python.
Old grammar file: file:///c%3A/Program%20Files/Microsoft%20VS%20Code/resources/app/extensions/python/syntaxes/MagicRegExp.tmLanguage.json.
New grammar file: file:///c%3A/Users/iulian/.vscode/extensions/tht13.python-0.2.3/syntaxes/Regular%20Expressions%20%28Python%29.tmLanguage
e.register @ TMSyntax.ts:47
TMSyntax.ts:47 Overwriting grammar scope name to file mapping for scope source.octave.
Old grammar file: file:///c%3A/Users/iulian/.vscode/extensions/leafvmaple.octave-0.1.1/syntaxes/octave.tmLanguage.json.
New grammar file: file:///c%3A/Users/iulian/.vscode/extensions/toasty-technologies.octave-0.0.3/syntaxes/octave.tmLanguage
e.register @ TMSyntax.ts:47
console.ts:134 [Extension Host] Python Extension: Display locator refreshing progress, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Notify locators are locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Detected refreshing of Interpreters, Arg 1: {}, Return Value: 
console.ts:134 [Extension Host] Python Extension: Display locator refreshing progress, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Notify locators are locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Detected refreshing of Interpreters, Arg 1: {}, Return Value: 
console.ts:134 [Extension Host] Python Extension: Display locator refreshing progress, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Notify locators are locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Detected refreshing of Interpreters, Arg 1: {}, Return Value: 
console.ts:134 [Extension Host] Python Extension: Display locator refreshing progress, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Notify locators are locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Detected refreshing of Interpreters, Arg 1: {}, Return Value: 
console.ts:134 [Extension Host] Python Extension: Display locator refreshing progress, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Notify locators are locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Detected refreshing of Interpreters, Arg 1: {}, Return Value: 
console.ts:134 [Extension Host] Python Extension: Create file systemwatcher with pattern *\python.exe
console.ts:134 [Extension Host] Python Extension: Create file systemwatcher with pattern *\*\python.exe
console.ts:134 [Extension Host] Python Extension: Display locator refreshing progress, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Notify locators are locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Detected refreshing of Interpreters, Arg 1: {}, Return Value: 
console.ts:134 [Extension Host] Python Extension: Display locator refreshing progress, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Notify locators are locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Detected refreshing of Interpreters, Arg 1: {}, Return Value: 
console.ts:134 [Extension Host] Python Extension: Display locator refreshing progress, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Notify locators are locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Detected refreshing of Interpreters, Arg 1: {}, Return Value: 
console.ts:134 [Extension Host] activate
console.ts:134 [Extension Host] Python Extension: Register Intepreter Watcher, Arg 1: {"$mid":1,"fsPath":"e:\\projects\\Python\\learn","external":"file:///e%3A/projects/Python/learn","path":"/e:/projects/Python/learn","scheme":"file"}, Return Value: 
console.ts:134 [Extension Host] Python Extension: Create file systemwatcher with pattern *\python.exe
console.ts:134 [Extension Host] Python Extension: Create file systemwatcher with pattern *\*\python.exe
console.ts:134 [Extension Host] Python Extension: Display locator refreshing progress, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Notify locators are locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Detected refreshing of Interpreters, Arg 1: {}, Return Value: 
console.ts:134 [Extension Host] Python Extension: Build the workspace interpreter watcher, Arg 1: {"$mid":1,"fsPath":"e:\\projects\\Python\\learn","external":"file:///e%3A/projects/Python/learn","path":"/e:/projects/Python/learn","scheme":"file"}, Return Value: UNABLE TO DETERMINE VALUE
console.ts:134 [Extension Host] Python Extension: Register Intepreter Watcher, Arg 1: undefined, Return Value: 
console.ts:134 [Extension Host] Python Extension: Build the workspace interpreter watcher, Arg 1: undefined, Return Value: UNABLE TO DETERMINE VALUE
console.ts:134 [Extension Host] Error: spawn jupyter ENOENT
	at _errnoException (util.js:1024:11)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
	at onErrorNT (internal/child_process.js:372:16)
	at _combinedTickCallback (internal/process/next_tick.js:138:11)
	at process._tickCallback (internal/process/next_tick.js:180:9)
t.log @ console.ts:134
console.ts:134 [Extension Host] Python Extension: Get language server folder name, , Return Value: "languageServer.0.1.66"
console.ts:134 [Extension Host] Lintings failed on open
t.log @ console.ts:134
console.ts:134 [Extension Host] File: file:///e%3A/projects/Python/learn/1.py
t.log @ console.ts:134
console.ts:134 [Extension Host] Message: TypeError: Cannot read property 'uri' of undefined
t.log @ console.ts:134
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Hide locator refreshing progress, , Return Value: 
console.ts:134 [Extension Host] Python Extension: All locators have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Hide locator refreshing progress, , Return Value: 
console.ts:134 [Extension Host] Python Extension: All locators have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Hide locator refreshing progress, , Return Value: 
console.ts:134 [Extension Host] Python Extension: All locators have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Hide locator refreshing progress, , Return Value: 
console.ts:134 [Extension Host] Python Extension: All locators have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Hide locator refreshing progress, , Return Value: 
console.ts:134 [Extension Host] Python Extension: All locators have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Hide locator refreshing progress, , Return Value: 
console.ts:134 [Extension Host] Python Extension: All locators have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Hide locator refreshing progress, , Return Value: 
console.ts:134 [Extension Host] Python Extension: All locators have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Hide locator refreshing progress, , Return Value: 
console.ts:134 [Extension Host] Python Extension: All locators have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Hide locator refreshing progress, , Return Value: 
console.ts:134 [Extension Host] Python Extension: All locators have completed locating, , Return Value: 
console.ts:134 [Extension Host] Python Extension: Checking whether locactors have completed locating, , Return Value: 
notificationsAlerts.ts:40 The Python Tools server crashed 5 times in the last 3 minutes. The server will not be restarted.
t.onDidNotificationChange @ notificationsAlerts.ts:40

```

**Comment by MikhailArkhipov** [comment]
Can we get list of files in the `languageServer` folder please.

**Comment by isurugiu** [comment]
I will this evening. Right now I don't have access to my home PC.

**Comment by isurugiu** [comment]
I have deleted the ms-python.python-2018.11.0 folder from the extensions directory, reinstalled the extension and it all went well.

**Comment by alfoquial** [comment]
I have the same problem.

VSCode Version: 1.30.0
OS Version: Fedora 28

Steps to Reproduce:

Install extension Python 2018.11.0
Open a python file

Does this issue occur when all extensions are disabled?: Yes

This is the console output
Starting Microsoft Python language server.
Downloading https://pvsc.azureedge.net/python-language-server-stable/Python-Language-Server-linux-x64.0.1.72.nupkg... complete.
Unpacking archive... done.
Cannot get required symbol EC_KEY_set_public_key_affine_coordinates from libssl
[Info - 19:50:22] Connection to server got closed. Server will restart.
....
Cannot get required symbol EC_KEY_set_public_key_affine_coordinates from libssl
[Error - 20:04:45] Connection to server got closed. Server will not be restarted.

I have uninstall vscode extension and remove directory and installed extension again to verify that it was not a corrupted download. The library that support libssl in Fedora 28 is compat-openssl10
Thanks

**Comment by MikhailArkhipov** [comment]
Looks like original issue was resolved, so closing.

@alfoquial - not all Linux flavors are supported by .NET Core. Some require manual install of dependencies. We try and check for distros on which LS may not be able to run, but it is work in progress. One option is to try and install complete .NET Core runtime and see if it places proper libssl on your system. Have a look at Fedora section here https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x

**Comment by jhidding** [comment]
This issue is still very much alive on Debian 10 (buster), since Debian buster doesn't include libssl1.0 in favour of version 1.1.

**Comment by holyoaks** [comment]
I have the same problem with the python extension. I've looked in the languageServer.0.4.71 folder for ms-python.python-2019.10.44104 and there is no System.Private.XML.Linq.dll present in that folder, which is the assembly specified in the application dependencies manifest. See image below, showing the dlls actually present in that folder.

![image](https://user-images.githubusercontent.com/5797525/67949726-3860d300-fbb6-11e9-99bb-b17899440270.png)

**Comment by jakebailey** [comment]
I don't think your issue is related. This issue was due to .NET not linking to OpenSSL 1.1, which we fixed by upgrading and rebuilding (almost immediately). Your issue seems like a download corruption, where you may want to try wiping out the LS install and letting the extension download it again.

**Comment by jakebailey** [comment]
Scratch that, that was a single comment above (which is definitely resolved). Either way, if redownloading it doesn't fix the issue, then please file a new issue, as this one is almost a year old.

**Comment by holyoaks** [comment]
@jakebailey wiping the folder and reinstalling the extension resolved the issue. Thank you!
